#!/Library/Frameworks/Python.framework/Versions/3.4/bin/python3
import magic
import sys

def main ():
	res = magic.from_file(sys.argv[1])
	print (sys.argv[1] + ": " + res.decode('utf-8') )

if __name__ == "__main__":
	main ()

